# Generated by Django 5.2.17 on 2026-09-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='badge',
            field=models.CharField(blank=True, help_text='e.g. New Release, Trending, Bestseller', max_length=50),
        ),
        migrations.AddField(
            model_name='design',
            name='image_url',
            field=models.URLField(blank=True, help_text='External or CDN image URL', max_length=1000),
        ),
        migrations.AddField(
            model_name='design',
            name='is_luxe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='design',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='design',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='design',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.9, max_digits=3),
        ),
        migrations.AddField(
            model_name='design',
            name='reviews_count',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='design',
            name='sku',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='design',
            name='subtitle',
            field=models.CharField(blank=True, help_text='e.g. Includes 3 Gold Foiled Inserts, RSVP', max_length=255),
        ),
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='designs/'),
        ),
    ]
