# Generated by Django 5.2.17 on 2026-09-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_design_badge_design_image_url_design_is_luxe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='design',
            name='color',
            field=models.CharField(blank=True, choices=[('maroon', 'Crimson Maroon'), ('gold', 'Royal Gold'), ('cream', 'Ivory Cream'), ('green', 'Pista / Olive Green'), ('pink', 'Rose Pink'), ('blue', 'Powder Blue')], max_length=50),
        ),
        migrations.AddField(
            model_name='design',
            name='craft_style',
            field=models.CharField(blank=True, choices=[('gold_foil', 'Gold Hot-Foil Stamping'), ('laser_cut', 'Laser Cut Filigree'), ('gatefold', 'Door & Gatefold Opening'), ('padded_velvet', 'Padded Velvet Hardcover'), ('rotating', 'Rotating Mechanism Card')], max_length=50),
        ),
        migrations.AddField(
            model_name='design',
            name='tradition',
            field=models.CharField(blank=True, choices=[('hindu', 'Hindu Wedding'), ('muslim', 'Muslim Nikah'), ('christian', 'Christian Nuptials'), ('sikh', 'Sikh Anand Karaj'), ('interfaith', 'Interfaith / Fusion')], max_length=50),
        ),
    ]
