from django.core.management.base import BaseCommand
from catalog.models import Category, Design
from django.utils.text import slugify


class Command(BaseCommand):
    help = "Seeds categories and designs for Siddhi Vinayaka Cards"

    def handle(self, *args, **options):
        self.stdout.write(self.style.SUCCESS("Starting database seeding..."))

        # Create Categories
        categories_data = [
            "Hindu Wedding Cards",
            "Muslim Nikah Stationery",
            "Christian Nuptial Cards",
            "Housewarming Ceremony",
            "Thread Ceremony",
            "Naming Ceremony",
            "Modern & Fusion",
        ]

        category_objs = {}
        for cat_name in categories_data:
            cat, created = Category.objects.get_or_create(
                name=cat_name,
                defaults={"slug": slugify(cat_name)},
            )
            category_objs[cat_name] = cat
            action = "Created" if created else "Found"
            self.stdout.write(f"{action} category: {cat.name}")

        # Create Designs
        designs_data = [
            {
                "name": "Blue Bride Groom Padded Laser Cut Royal Wedding Invitation",
                "sku": "KAA06220",
                "price": 216.60,
                "original_price": 270.00,
                "badge": "New Release",
                "rating": 4.9,
                "reviews_count": 128,
                "subtitle": "Includes 3 Gold Foiled Inserts, RSVP & Padded Outer Envelope",
                "description": "Midnight sapphire blue padded bridal groom laser cut royal Indian wedding invitation suite with intricate jali archways and gold metallic foil details.",
                "image_url": "https://lh3.googleusercontent.com/aida-public/AB6AXuAgPNMLsbOIqm2of7aTS3Sllw44I7pWTXtimDAvLJ2tfobNAJjusQYwv971i7U1Jf5RKR-67QHkRlWJ3TaphoUZ8AQsF9Zy4nZqSSbLexrDTF87_lACmqzUl8UFCYQxuzWuOqWBNrAe7lPYpBcb9uqbrk70_ArZKkIqV377DUp_skXbWR7LROcFg5CAzdNTm-rKQmWmqdB5Xxr7lNXq-yaYNSe6p1pLmJdTY9WZlPRq7_oSNS_Jf447Gg",
                "category": category_objs["Hindu Wedding Cards"],
                "tradition": "hindu",
                "craft_style": "laser_cut",
                "color": "blue",
                "is_new": True,
                "is_sale": False,
                "is_luxe": True,
            },
            {
                "name": "Rajputana Heritage Velvet Padded Floral Wedding Suite",
                "sku": "RJT90441",
                "price": 184.50,
                "original_price": 230.00,
                "badge": "Trending",
                "rating": 5.0,
                "reviews_count": 94,
                "subtitle": "Sculpted Gold Ganesha Crest, 4 Tracing Inserts & Wax Monogram",
                "description": "Crimson maroon and antique gold regal Rajputana wedding card set with hand-stamped wax seal, peacock motifs, and thick textured cotton rag paper.",
                "image_url": "https://lh3.googleusercontent.com/aida-public/AB6AXuDJanleUXCpYPrImHRPEKhmudW-mSxsTVTuyXJF-NNPmgVxOJf0o2PBm7Cm9VB5LvUzybg6hlxQYsRRunAiFiXZuM4ArnvWsZXMdrVsLBOLsr-Sl6FZYmJBC4lsIIJDRIe10GxNoeQcjz5CCBDYJ9CpJEmlTc-BnaagBy6NXA8MwW2z6HyFLCdSGpPp6zNL_ZndiwQ2w0f6bIQZrOMptBDy54CLBfjIFf3CoH1YDbI2CgN2Yvd2lNYp7A",
                "category": category_objs["Hindu Wedding Cards"],
                "tradition": "hindu",
                "craft_style": "padded_velvet",
                "color": "maroon",
                "is_new": False,
                "is_sale": False,
                "is_luxe": True,
            },
            {
                "name": "Pearl White Royal Elephant Floral Gilded Invitation",
                "sku": "KRC31160",
                "price": 119.00,
                "original_price": 160.00,
                "badge": "Bestseller",
                "rating": 4.8,
                "reviews_count": 210,
                "subtitle": "Multi-fold Organza Satin Ribbon Sleeve with Custom Monogram Seal",
                "description": "Ivory pearl shimmer wedding invitation suite with pastel botanical floral borders, golden calligraphy and delicate organza ribbon ties.",
                "image_url": "https://lh3.googleusercontent.com/aida-public/AB6AXuDNn9nqHajzlnW5zJMvfjm-K1S0_lpiFS8rtZAF-A-_0FUCZys9QovqTlvv7pYxjKiQq-zI5MU2P0l6UAuhX9bumMnErA6HsAFFyXDEx0osOMzAr2_FLC1z-h3ZyBeohPywHrdXMCROaPoEb-nJ1R0lOyCmAenw4CKvf6RuD7Ow5nI0vt2KxuXlhMM6pcItGpGzhyb2CNzzQvBQ_5Xq4AeNoNoLuvfiYHsiMeD4_ByaKgE2EaB9em_tqg",
                "category": category_objs["Hindu Wedding Cards"],
                "tradition": "hindu",
                "craft_style": "gold_foil",
                "color": "cream",
                "is_new": False,
                "is_sale": False,
                "is_luxe": False,
            },
            {
                "name": "Cream Padded Bride Groom Wedding Card",
                "sku": "KRC31070",
                "price": 96.00,
                "original_price": 216.00,
                "badge": "Sale",
                "rating": 4.7,
                "reviews_count": 88,
                "subtitle": "Includes 2 Inserts & Gold Foil Outer Envelope",
                "description": "Cream padded bride groom wedding invitation card with gold foil embossing and auspicious chariot procession artwork.",
                "image_url": "https://lh3.googleusercontent.com/aida-public/AB6AXuCnx2eH6AzwfgkP6zxztZDwpY2HgbbCWFd9USbP0OR4EyOFV-a2Za5kNnIa36VMo3uCkETmfG9PROw0wNrDBYgIsjM4cPDDi32ZAG9Af2ArAoS1NHC8ZAd50HYmxUm3fsebgmpr0MUWyLA1HGmZZD9ICy7Z1a8UPtnbVeqX1MECJ0P04uCvglnuyox6Tx6pbhnl0zllqtfAEGYxpMZl-N8-CCnfhXuxSLYpPsJntTJGkbUfpt01rbim9Q",
                "category": category_objs["Hindu Wedding Cards"],
                "tradition": "hindu",
                "craft_style": "padded_velvet",
                "color": "cream",
                "is_new": False,
                "is_sale": True,
                "is_luxe": False,
            },
            {
                "name": "Blue Premium Padded Marriage Invitation",
                "sku": "KPR24390",
                "price": 149.00,
                "original_price": 450.00,
                "badge": "Sale",
                "rating": 4.9,
                "reviews_count": 142,
                "subtitle": "Laser Cut Peacock Window with Gilded Arch Inserts",
                "description": "Royal teal blue premium padded marriage invitation card with laser cut window revealing gilded gold peacock crest.",
                "image_url": "https://lh3.googleusercontent.com/aida-public/AB6AXuAw1LdnN73wXcbJyY7QboCMss8kvHTKSp-eElqDavy9_MqTrzWJH2CC8SA6AO5Fblc-Y_kogjjkbL-zAAhXtVKpAlnYP0gNYPBs0nieMcfYhrT4ln6bAZiRxYmkXPPd36S6YPDe34q9Ve9S6O0NOQDXetm2BYY1tho7gK1eeRHLPjhQRzHLk5-2X_aaKvWm-a-bia1DkSiByfHzi8yqVkLKMSsKIKIDKL-_JjcJVIZvYgy3rCe1PIvwLQ",
                "category": category_objs["Hindu Wedding Cards"],
                "tradition": "hindu",
                "craft_style": "laser_cut",
                "color": "blue",
                "is_new": False,
                "is_sale": True,
                "is_luxe": True,
            },
            {
                "name": "Grey Padded Floral Palace Wedding Card",
                "sku": "KRC51040",
                "price": 99.00,
                "original_price": 222.00,
                "badge": "Sale",
                "rating": 4.8,
                "reviews_count": 76,
                "subtitle": "Delicate Laser Cut Gatefold Opening with Gold Foiling",
                "description": "Grey and sage green padded floral palace wedding card with delicate laser cut gatefold opening and gold foiling.",
                "image_url": "https://lh3.googleusercontent.com/aida-public/AB6AXuCZjXbOoQ29qeVvpmMU_nLhmvXyi1_shDVROs6slT6PlZm-oZbNdmJUZChNIR0fDh7H56WHBsv_ZZ1FBQzuuIzrTl7wAzayDc4B0Q1IJiTRVR9SwS9WWZIYDCh62jdZVOqTshXFJbqWU102o5HMSGJUWrV-eAZHCHmb77XrgxZiVPayvAM93wS2b7Wt_hdB5MF6_YoeI3OzlJfvRHa5ignaVXM5OwYFPC5lvyJQjNesyQHLSovAvsNmkA",
                "category": category_objs["Hindu Wedding Cards"],
                "tradition": "hindu",
                "craft_style": "gatefold",
                "color": "cream",
                "is_new": False,
                "is_sale": True,
                "is_luxe": False,
            },
            {
                "name": "Lavender Padded Floral Bride Groom Card",
                "sku": "KRC31360",
                "price": 119.00,
                "original_price": 270.00,
                "badge": "Sale",
                "rating": 4.9,
                "reviews_count": 105,
                "subtitle": "Antique Rose Gold Foil Details with Botanical Illustrations",
                "description": "Lavender padded floral bride groom wedding card with silver and antique rose gold foil details and botanical illustrations.",
                "image_url": "https://lh3.googleusercontent.com/aida-public/AB6AXuCU6tfBU3KSqvvkVUTm_NASuCB2_6f6nMRmbdwGzmkfL1CmTiOJr9QavFa2FRjMz6XgExMfuuMs1Wwtne4Un5a22xqV1_rSRq_yx9BNKcrItV-JoIHyI1d53xvCapeNdnTA65Ih6OIOLntFIkOn8lO8vspCwY-vQqkSPA6yegxs5YvCLGr_Ck3iCQAeG4tLugdHfqeudANqKWcncADiOgO1Ax2cTy685_A7Wt9T0bIj0bBqa27U7uGUbQ",
                "category": category_objs["Hindu Wedding Cards"],
                "tradition": "hindu",
                "craft_style": "padded_velvet",
                "color": "pink",
                "is_new": False,
                "is_sale": True,
                "is_luxe": False,
            },
            {
                "name": "Olive Green Bride Groom Wedding Card",
                "sku": "KNKN6313",
                "price": 50.25,
                "original_price": 59.00,
                "badge": "Popular",
                "rating": 4.8,
                "reviews_count": 142,
                "subtitle": "Includes 2 Inserts & Matching Padded Outer Bag",
                "description": "Traditional South Indian olive green wedding card with gold foiled Ganesha motif, padded envelope, and rich botanical border artwork.",
                "image_url": "https://lh3.googleusercontent.com/aida-public/AB6AXuAq__qyokvdptPzp5iuCBbd36EbvOCzVTZNQSymzMc05cFIQeRmiaqT8Fmx1widLN84aoSgjQsvLVXOU55-gyeL0bWmohKJUJGVy8Vc1fuiUruCruCUpvu80gL3t_JDiCLyzbR0SOiwmSLBBL8Flab-4LruepbbvffPY-wxIhvkGKmjBjfpmr40pWr8Qn4JlSoZfI1u2R2ISW0SXOk603OciEpMIxu0CQTnsCrbp3sIN2EE1wRNi-M7Pg",
                "category": category_objs["Hindu Wedding Cards"],
                "tradition": "hindu",
                "craft_style": "gold_foil",
                "color": "green",
                "is_new": False,
                "is_sale": False,
                "is_luxe": False,
            },
            {
                "name": "White Embossed Monogram Floral Card",
                "sku": "KRE26940",
                "price": 64.60,
                "original_price": 76.00,
                "badge": "Elegant",
                "rating": 5.0,
                "reviews_count": 98,
                "subtitle": "Self-Embossed Monogram & Pastel Floral Inserts",
                "description": "Exquisite pearl white embossed wedding card with custom couple monogram, metallic gold lace foil border, and pastel floral insert leaves.",
                "image_url": "https://lh3.googleusercontent.com/aida-public/AB6AXuBIZO7gS-mmlu9rIDYhdv_yMgq7U5ItjSK-Epb0Vn8ETmMQOwcd0eFEPiEB0qQyptlb9MQeVQU1qKyS9v58hNYDH60Fb8-fKyq7jT1sSG379xi72p8-AhOf9qRFx5S6Y6-b0Qv_2EQ4JXQYUzKNVZeZtGFD9pdy60boOZLF0nNV4WXqIhhNolM3O8ZUcY_MeFIliExUZxomnLyJ5KAnvyUZ3UQg5Ld7FgeUFT4Qa7sPoJ7eCXy3avwzPg",
                "category": category_objs["Hindu Wedding Cards"],
                "tradition": "hindu",
                "craft_style": "gold_foil",
                "color": "cream",
                "is_new": False,
                "is_sale": False,
                "is_luxe": False,
            },
            {
                "name": "White Gold Balaji Padmavathi Card",
                "sku": "KNK7079O",
                "price": 22.80,
                "original_price": 27.00,
                "badge": "Bestseller",
                "rating": 5.0,
                "reviews_count": 310,
                "subtitle": "Economical Heritage Sacred Shloka Print Card",
                "description": "Traditional Tirupati Balaji Padmavathi Hindu wedding invitation card in pure white and sacred gold foiling with delicate red borders.",
                "image_url": "https://lh3.googleusercontent.com/aida-public/AB6AXuBdGglnEYp6M-HfLIADnr8p66IAPwDVh6LzM3KjrGpRQqurdOj5_yB0KYwok7HG0MWmphU24-dt2Y8URFEnnyqwV4oj6OV-nx6BGDVmHGx2lu440JcF0cRcItlEeCVKwcr8pJj7j7RpmQ0ZqHltgdivwXfIADBW-dLAeUN_blmo2f4DFYBQLNOMi4W5V_IspTKBscBpN29ZQeeXUMNO4uBcr37Xat-xQjlHE_us7OWuYDy_C3t4KTyQrQ",
                "category": category_objs["Hindu Wedding Cards"],
                "tradition": "hindu",
                "craft_style": "gold_foil",
                "color": "cream",
                "is_new": False,
                "is_sale": False,
                "is_luxe": False,
            },
            {
                "name": "Cream Door Style Peacock Wedding Card",
                "sku": "KNKY2601",
                "price": 32.30,
                "original_price": 38.00,
                "badge": "Gatefold",
                "rating": 4.7,
                "reviews_count": 86,
                "subtitle": "Double Door Fold with Regal Peacock Motif",
                "description": "Warm cream double door folding invitation card featuring regal peacock motifs in metallic gold and jewel-toned teal.",
                "image_url": "https://lh3.googleusercontent.com/aida-public/AB6AXuBjYPm1pYLQs--FvsSIZOm8CiipAfxtsF0dMVlqOy2rFtKYhSnhRfGDyM2uqU-lsRtRX9aJppGQHzTFgcTPfpAnh24xcc_DuzyfPxINDqWtwXpd39LTZ_OKo4olAAFgdg0X0NC6VajvVi12pjn86FuhNzZhkORFV5kGNV0TRZXqT5EVUHSHNbpHbl1Jh3Atzez0Cf9OCl2i_2FOxxxX4yZjUFLL_WPuXG15D_leSkQtnCzLq9ErJeD4KA",
                "category": category_objs["Hindu Wedding Cards"],
                "tradition": "hindu",
                "craft_style": "gatefold",
                "color": "cream",
                "is_new": False,
                "is_sale": False,
                "is_luxe": False,
            },
            {
                "name": "Blue Floral Rotating Wheel Invitation",
                "sku": "KNFO8402",
                "price": 26.60,
                "original_price": 28.00,
                "badge": "Interactive",
                "rating": 4.8,
                "reviews_count": 110,
                "subtitle": "Interactive Rotating Wheel Revealing Ceremony Functions",
                "description": "Creative blue floral interactive wedding card with rotating wheel revealing ceremony functions, sangeet, reception, and wedding date.",
                "image_url": "https://lh3.googleusercontent.com/aida-public/AB6AXuBSNLUlQvBrsE4VshR9pFJxY_SzK2HSuNzJJtbEMBRYZB2AoYmQaqog--5cpbYDjOv2AkoyoRpcxMnSD2wZCj8wvMLtVhCRlginjPYKvVwagYlfBARKOiUojnX4JULjgphP24Lkv8SnrJOkVHYz317kzMgyMtzdsrTJG8K3liqVBxZOevdihgmDfkC_h4sUTIjScDZ8LdDzsmRQuNTJ55WBfBgU_kQAKcofO8Fab_9YGVySzARMp1G0-A",
                "category": category_objs["Modern & Fusion"],
                "tradition": "interfaith",
                "craft_style": "rotating",
                "color": "blue",
                "is_new": False,
                "is_sale": False,
                "is_luxe": False,
            },
        ]

        for item in designs_data:
            design, created = Design.objects.update_or_create(
                sku=item["sku"],
                defaults=item,
            )
            action = "Created" if created else "Updated"
            self.stdout.write(f"{action} design: {design.name} (SKU: {design.sku})")

        self.stdout.write(self.style.SUCCESS("Database seeding completed successfully!"))
